#! /bin/bash -login
#SBATCH -J RNAsignal
#SBATCH -t 11-00:00:00
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 2  
#SBATCH -p general
#SBATCH --mem=2gb
#SBATCH -o "%x-%j.out"

## Exit if any command fails
set -e

## Load required modules
module load python/3.9.6

## Create and activate virtual environment with requirements
python3 -m venv env && source env/bin/activate && pip3 install -r config/requirements.txt


## Make directory for slurm logs
mkdir -p output/logs_slurm


## Execute RNApipeCore snakemake workflow


snakemake -s snakefiles/rna_signal.snakefile --configfile "config/rna_prcoess.yaml" --cluster-config "config/cluster.yaml" --cluster "sbatch -J {cluster.name} -p {cluster.partition} -t {cluster.time} -c {cluster.cpusPerTask} --mem-per-cpu={cluster.memPerCpu} -N {cluster.nodes} --output {cluster.output} --error {cluster.error} --parsable" --cluster-status snakefiles/utils/status.py -j 200 --max-jobs-per-second 0.5 --max-status-checks-per-second 1 --rerun-incomplete -p --latency-wait 500 

## Success message
echo "Workflow completed successfully!"
